/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/Cycl0o0/OpenDeezer/v2/corelib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 9 "connect.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 13 "deezercore.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"

#line 6 "webremote.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void DZSetClientInfo(char* client, char* device);
extern char* DZNowPlayingJSON(void);
extern char* DZDiscoverDevices(int timeoutMS);
extern int DZConnectDevice(char* addr);
extern void DZDisconnectDevice(void);
extern char* DZConnectedDevice(void);
extern void DZFree(char* s);
extern unsigned char* DZFetch(char* url, int* outLen);
extern void DZFreeBytes(unsigned char* p);
extern int DZInit(char* arl);
extern int DZLoginErrorKind(void);
extern char* DZLastErrorJSON(void);
extern void DZSetQuality(int level);
extern int DZQuality(void);
extern int DZHighQuality(void);
extern char* DZFormat(void);
extern char* DZUserID(void);
extern char* DZFavoritesJSON(void);
extern char* DZFavoriteIDsJSON(void);
extern char* DZPlaylistsJSON(void);
extern char* DZPlaylistTracksJSON(char* id);
extern char* DZAlbumTracksJSON(char* id);
extern char* DZSearchJSON(char* q);
extern int DZPlay(char* trackID, long long durationMS);
extern void DZPause(void);
extern void DZResume(void);
extern void DZTogglePause(void);
extern void DZStop(void);
extern void DZSeek(long long ms);
extern void DZSetRepeat(int mode);
extern void DZSetShuffle(int on);
extern char* DZGetRepeat(void);
extern int DZGetShuffle(void);
extern int DZState(void);
extern long long DZPositionMS(void);
extern long long DZDurationMS(void);
extern void DZSetVolume(double v);
extern double DZVolume(void);
extern int DZFinishedCount(void);
extern char* DZDownloadTrack(char* trackID, char* destDir);
extern char* DZDownloadAlbum(char* id);
extern char* DZDownloadPlaylist(char* id);
extern char* DZDownloadDir(void);
extern int DZSetDownloadDir(char* path);
extern int DZMediaCacheMB(void);
extern int DZSetMediaCacheMB(int mb);
extern int DZIsPreview(void);
extern int DZSetAdsDisabled(int disabled);
extern int DZAdsDisabled(void);
extern char* DZAccountJSON(void);
extern char* DZProfilesJSON(void);
extern int DZSwitchProfile(char* userID);
extern char* DZChartsJSON(void);
extern char* DZHomeJSON(void);
extern char* DZCheckUpdateJSON(void);
extern char* DZArtistTopJSON(char* id);
extern char* DZArtistProfileJSON(char* id);
extern char* DZLyricsJSON(char* trackID);
extern void DZSetReplayGain(int on);
extern int DZReplayGain(void);
extern int DZAddFavorite(char* trackID);
extern int DZRemoveFavorite(char* trackID);
extern int DZAddToPlaylist(char* playlistID, char* trackID);
extern int DZRemoveFromPlaylist(char* playlistID, char* trackID);
extern char* DZCreatePlaylist(char* title);
extern int DZRenamePlaylist(char* playlistID, char* title);
extern int DZDeletePlaylist(char* playlistID);
extern char* DZFlowJSON(void);
extern char* DZTrackMixJSON(char* id);
extern char* DZArtistMixJSON(char* id);
extern char* DZHistoryRecentJSON(int n);
extern char* DZHistoryStatsJSON(int sinceDays);
extern char* DZSearchPodcastsJSON(char* q);
extern char* DZPodcastEpisodesJSON(char* podcastID);
extern char* DZAudioDevicesJSON(void);
extern int DZSetAudioDevice(char* id);
extern char* DZCurrentAudioDevice(void);
extern void DZSetGapless(int on);
extern int DZGapless(void);
extern void DZSetCrossfadeMS(int ms);
extern int DZCrossfadeMS(void);
extern void DZSetSleepTimer(int minutes, int endOfTrack);
extern void DZCancelSleepTimer(void);
extern int DZSleepTimerActive(void);
extern int DZSleepTimerEndOfTrack(void);
extern long long DZSleepTimerRemainingMS(void);
extern void DZPreload(char* trackID, long long durationMS);
extern int DZPlayEpisode(char* episodeID, long long durationMS);
extern char* DZEQJSON(void);
extern int DZSetEQJSON(char* js);
extern void DZClearPreload(void);
extern int DZQueueSet(char* js);
extern void DZQueueSetIndex(int i);
extern int DZQueueIndex(void);
extern long long DZQueueVersion(void);
extern char* DZQueueJSON(void);
extern void DZQueueRemove(int i);
extern void DZQueueMove(int from, int to);
extern void DZQueueInsertNext(char* js);
extern char* DZDownloadForOffline(char* trackID);
extern char* DZControlConfigJSON(void);
extern void DZSetControlConfig(int enabled, char* addr, char* token);
extern void DZWebRemoteSetEnabled(int on);
extern char* DZWebRemoteInfoJSON(void);
extern unsigned char* DZWebRemoteQRPNG(int* outLen);

#ifdef __cplusplus
}
#endif
